import localFont from "next/font/local";
import "./globals.css";

const comfortaa = localFont({
  src: [
    {
      path: "./fonts/comfortaa/comfortaa-variable.ttf",
      weight: "300 700",
      style: "normal",
    },
  ],
  variable: "--font-comfortaa",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" className={`${comfortaa.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}